FROM python:3.10-slim AS builder

WORKDIR /usr/src/app

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN find . -type f -regex ".*\.py$" -exec sed -i -E  "s/(Path\()None, /\1/g" {} \;
RUN pip install --no-cache-dir .


FROM python:3.10-slim AS test_runner
WORKDIR /tmp
COPY --from=builder /venv /venv
COPY --from=builder /usr/src/app/tests tests
ENV PATH=/venv/bin:$PATH

# install test dependencies
# RUN pip install pytest

# run tests
# RUN pytest tests


FROM python:3.10-slim AS service
WORKDIR /root/app/site-packages
COPY --from=test_runner /venv /venv
ENV PATH=/venv/bin:$PATH
